// Adapter: Codex CLI — isolated CODEX_HOME under generated/, launched via
// bin/zcode-codex.cmd|.sh. The user's real ~/.codex is never touched; skills,
// rules and MCP servers outside the isolated home are unaffected (difference
// documented in harnesses/README.md).
import { existsSync, mkdirSync } from "node:fs";
import { join } from "node:path";
import { commitFile } from "../../lib/edit.mjs";

export default {
  id: "codex",
  label: "Codex CLI",
  protocol: "Responses API (wire_api = \"responses\") via local proxy",
  primarySource: "https://developers.openai.com/codex/config-advanced/ (checked 2026-09-13; codex 0.153.4 rejects wire_api=\"chat\")",
  detect: (home) => existsSync(join(home, ".codex")) || detectOnPath("codex"),

  apply(ctx, tx, log) {
    const port = ctx.port();
    const home = join(ctx.generated, "codex-home");
    mkdirSync(home, { recursive: true });
    const mcpEntry = ctx.root.replace(/\\/g, "/");
    const toml = `# Generated by zcode-kit — isolated CODEX_HOME for the ZCode kit.
# Your normal ~/.codex is untouched; use bin\\zcode-codex.cmd to enter this setup.
model = "glm-5.3"
model_provider = "zcode"

[model_providers.zcode]
name = "ZCode (local proxy)"
base_url = "http://127.0.0.1:${port}/v1"
env_key = "ZCODE_PROXY_KEY"
wire_api = "responses"

[mcp_servers.zcode-harness]
command = "node"
args = ["${mcpEntry}/mcp/zcode-harness-mcp/dist/index.js", "--stdio"]
`;
    const configPath = join(home, "config.toml");
    const { wrote } = commitFile(ctx, tx, configPath, toml);
    if (wrote) {
      log(`  wrote ${configPath} (model provider + zcode-harness MCP)`);
      log('  use via: bin\\zcode-codex.cmd  (e.g. bin\\zcode-codex.cmd exec "task")');
    }
    return { changed: wrote };
  },

  verify(ctx) {
    return [{ name: "codex adapter artifact", ok: existsSync(join(ctx.generated, "codex-home", "config.toml")), detail: "generated/codex-home/config.toml" }];
  },
};

import { execFileSync } from "node:child_process";
function detectOnPath(cmd) {
  try {
    execFileSync(process.platform === "win32" ? "where" : "which", [cmd], { stdio: "pipe" });
    return true;
  } catch {
    return false;
  }
}
